services:
  # Nuxt PWA Application
  pwa:
    build:
      context: ./pwa
    volumes:
      - ./:/app/
    depends_on:
      - postgres
      - minio
    command: sh -c "rm -rf /tmp/nitro && npm run dev"

  # Spring Boot API Application
  api:
    build:
      context: ./api/
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_DB=volo_db
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
      - POSTGRES_USER=${POSTGRES_USER:-app}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # MinIO Object Storage
  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    environment:
      MINIO_ROOT_USER: volodb
      MINIO_ROOT_PASSWORD: test1234
      #MINIO_ACCESS_KEY: minioadmin # change to your desired access key
      #MINIO_SECRET_KEY: minioadmin # change to your desired secret key
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/volodb/data:/data
    depends_on:
      - postgres

  # Caddy Reverse Proxy with SSL
  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - pwa
      - api

volumes:
  caddy_data:
  caddy_config:
  db_data:
